# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish release to NPM

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: |
      github.event.pull_request.merged &&
      github.ref == 'master' &&
      contains(github.event.pull_request.labels.*.name, 'publish')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Configure Github details
        run: |
          git config user.name ${{ env.GITHUB_ACTOR }}
          git config user.email gh-actions-${{ GITHUB_ACTOR }}@github.com
      - name: Install NPM dependencies
        run: npm ci
      - name: "NPM: Create version tag"
        run: |
          echo "version_tag=$( npm version patch --force -m "Version %s" )" >> $GITHUB_ENV
      - name: "NPM: Publish"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
      - name: Push tags to Github
        run: |
          git remote add gh-origin https://${{ env.GITHUB_ACTOR }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.GITHUB_REPOSITORY }}.git
          git push gh-origin HEAD:master --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.version_tag }}
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
